### ISSUE TITLE
Allow Script to run at AWS Org level

### ISSUE THREAD

**Issue by soggysec** [CrowdStrike/Cloud-Benchmark#10]
Run Cloud Benchmark script at AWS Org Level (and other cloud equivalents) to more easily obtain numbers.

**Comment by musayev-io** [comment]
I like this idea! We'll definitely take a look at this to see how it can be accomplished. For AWS, this should be pretty simple since AWS Organizations creates a role in all child accounts (by the default name `OrganizationAccountAccessRole`).

**Comment by carlosmmatos** [comment]
AWS Org update should be done with #17

**Comment by isimluk** [comment]
Right, this is issue can now be closed.
