### ISSUE TITLE
add boto3 in requirements

### ISSUE THREAD

**Issue by pie-r** [CrowdStrike/Cloud-Benchmark#8]
The AWS script can not work without boto3.

And boto3 is missing in the requirements.txt.

**Comment by jshcodes** [comment]
Hi @pie-r -

Thank you for pointing this out, we will get this updated today! :smile:

> This issue does not impact Cloud Shell execution of this script as documented in the README, as AWS Cloud Shell has the AWS CLI / boto3 pre-installed.
